[graph]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true

[advisories]
unmaintained = "workspace"
unsound = "all"
ignore = []

[licenses]
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "Unicode-3.0",
]

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

[bans.std-replacements]
scope = "workspace"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
